## Содержание
- [Примеры создания массивов](#примеры-создания-массивов)
- [Демонстрация атрибутов](#демонстрация-атрибутов)
- [Примеры индексирования и срезов](#примеры-индексирования-и-срезов)
- [Векторные операции и базовые статистики](#векторные-операции-и-базовые-статистики)

In [1]:
import numpy as np

# Примеры создания массивов

In [ ]:
lst = [1,3,2,4,1,5]
array_from_list = np.array(lst)

a = np.arange(10)
b = np.ones(2)
c = np.zeros(3)
# соответственно функции создания массива из списка, с последовательными числами, заполненный нулями и единицами.
array_from_list,a,b,c

(array([1, 3, 2, 4, 1, 5]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1., 1.]),
 array([0., 0., 0.]))

# Демонстрация атрибутов

In [ ]:
a = np.array([[1,2,3],
              [3,5,6],
              [1,7,9]])
# вывод формы массива и типа значений его элементов
a.shape, a.dtype 

((3, 3), dtype('int64'))

# Примеры индексирования и срезов

In [8]:
b = a[1] # второй подмассив
c = a[-1][-1] # последний элемент двумерного массива - 9 (число)
g = a[0][:2] # из первого подмассива элементы с 0 по 2 невключительн

b,c,g

(array([3, 5, 6]), np.int64(9), array([1, 2]))

# Векторные операции и базовые статистики

In [ ]:
a = np.array([2,3,5])
b = np.array([1,7,9])

c = a * b # поэлементное умножение
g = a + b #поэлементное сложение
f = a @ b.T  # матричное умножение
j = np.stack([a,b],axis = 0) # конкатенация

c, g, f,j

(array([ 2, 21, 45]),
 array([ 3, 10, 14]),
 np.int64(68),
 array([[2, 3, 5],
        [1, 7, 9]]))

In [ ]:
m = j.mean()
v = j.var(axis = 0)
s = j.std(axis = 0)
# расчет среднего, дисперсии и стандартного отклонения
m,v,s

(np.float64(4.5), array([0.25, 4.  , 4.  ]), array([0.5, 2. , 2. ]))